apiVersion: v1
kind: ServiceAccount
metadata:
  name: voting-app
  labels:
    app.kubernetes.io/part-of: securecicd
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
